# Generated by Django 4.0.3 on 2022-03-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prof',
            name='modules',
        ),
        migrations.AddField(
            model_name='module',
            name='profs',
            field=models.ManyToManyField(to='app.prof'),
        ),
    ]
